TestsRun tests for updating and completing a task
kimitaWanjohi/todo-list-microverse pull request #9
Opened 2023-04-07 19:52 UTC by 0sugo

test for editing the task description.
test for updating an item's 'completed' status.

2023-04-07 20:21 UTC, huseyinbiyik requested changes
Hi team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Tests are added for editing, and marking completed to dos 👍 
- Linter set up well and checks pass 🟢
- Github flow followed 👌


## Required Changes ♻️
<img width="367" alt="Screenshot 2023-04-07 at 11 19 35 PM" src="https://user-images.githubusercontent.com/25887253/230673857-9f18d4cf-ff94-414b-bddc-f1c9d1c89b69.png">
-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML" 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 20:21 UTC, huseyinbiyik commented on test/crud.test.js
> +  describe('editDescription', () => {
Great job guys 👍  But let's add a test for the Clear All Completed function as the requirements say. 
<img width="752" alt="Screenshot 2023-04-07 at 11 15 49 PM" src="https://user-images.githubusercontent.com/25887253/230673371-562b6714-14f5-4b55-9ced-f75e9f728a72.png">

2023-04-07 21:02 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @kimitaWanjohi 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 21:02 UTC, anagudelogu commented on test/crud.test.js
> +  });
- [ ] You did great working on the previous reviewer's suggestions! 🚀 However, this test doesn't provide a lot of value or confidence to your code, yes, you're adding two to-do's, and you're clearing all completed, but it isn't proving the real functionality of the function since there wasn't any completed To-do. 🤔 

I suggest that you add the same two tasks, but assign one as completed, then clear all completed, and finally, assert that the `todos` list now just has one item! 🤓 🔧

2023-04-08 07:46 UTC, BenMukebo approved these changes
### Hi @0sugo, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
* Your Pull Request has a proper title and description. ✔️  
* No Linter errors :heavy_check_mark: 
* Test the function for editing the task description.
* Test the function for updating an item's 'completed' status. ✔️  
* Test the "Clear all completed" function. ✔️  


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-09 05:36 UTC, merged